# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py312,pypy3,ruff

[testenv]
deps = pytest>=6.2.0
commands = pytest {posargs:tests}

[testenv:ruff]
skip_install = true
deps = ruff
commands =
    ruff check src tests
    ruff format --check src tests
